### ISSUE TITLE
Example throws a "Cannot find 'cryptoAES' in scope when building for iOS

### ISSUE THREAD

**Issue by ivanhercaz** [ogabrielinacio/esp_provisioning_ble#1]
Hi, @ogabrielinacio!
First of all, thank you for this package. It is very useful for me at this moment and I like it seems there is a lot of work on it 👏🏽 👏🏽 

Before to use the package I want to be sure the example runs fine in Android and iOS. I already tested Android and it works nice. However, iOS is giving me a fight... I admit that I am new developing for iOS and sometimes I found issues/things that are more related with my poor knowledge about its ecosystem, than with a real bug. Thus this report may be a bug or just my poor knowledge.

The steps I am following to deploy in my physical iPad are:

1. Clone the repository, open `example` directory in VSCode.
2. Open XCode and set myself as the team member.
3. Again in VSCode, run "Start without debugging" (also tested using `flutter run`).

Then I get the next error:

```
[example] flutter run                                                                             main  ✭ ✱
Launching lib/main.dart on iPad de X in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:
<XCODE_PROJECT_ID>
Running pod install...                                           1.430ms
Running Xcode build...                                                  
Xcode build done.                                            6,0s
Failed to build iOS app
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Cannot find 'cryptoAES' in scope
/Users/maufo/dev/flutter/esp_provisioning_ble/ios/Classes/EspProvisioningBlePlugin.swift:18:8

Swift Compiler Error (Xcode): Value of type 'EspProvisioningBlePlugin' has no member 'cryptoAES'
/Users/maufo/dev/flutter/esp_provisioning_ble/ios/Classes/EspProvisioningBlePlugin.swift:23:35

Error launching application on iPad de X.
```

If I run it in Xcode (Products > Run), but I get `Module 'app_settings' not found` (I really don't know if it is related with the same issue (if you consider, I can open another one for that).

After reading a lot about both errors, I really don't understand why it isn't finding `cryptoAES` in the scope, although I don't know Swift) and the `app_settings` error still there. For example, I read [this StackOverflow question](https://stackoverflow.com/q/66227407/473597) and tried to follow some suggestions about to clean environment, so I tried the next steps:

1. Delete `ios/Pods`, `ios/.symlinks` and `podfile.lock`
2. `flutter clean`
3. `flutter pub get`
4. `cd ios`
5. `pod install --repo-update`

And finally try to run again in both, VSCode and Xcode, both with the same results.

Have you any idea about it?

## Technical info

```
OS: macOS 14.0 23A344 arm64 
Host: Macmini9,1 
Kernel: 23.0.0 
CPU: Apple M1 
GPU: Apple M1 
Memory: 1485MiB / 8192MiB 
```

## Development info

```
Xcode 15.0.1
VSCode 1.83
```

```
Flutter 3.16.0-18.0.pre.88 • channel master • https://github.com/flutter/flutter.git
Framework • revision a4ec6278b1 (12 hours ago) • 2023-10-28 02:47:25 -0400
Engine • revision 84dcb4fb93
Tools • Dart 3.3.0 (build 3.3.0-71.0.dev) • DevTools 2.28.1
```

**Comment by ogabrielinacio** [comment]
Hello, @ivanhercaz 

Firstly, thank you for your compliments. I'm delighted that my package has received such recognition.

I believe I have identified the solution to your issue, which appears to be a code bug. Unfortunately, I won't be able to address it until November 2, 2023. On that day, I will have access to a MacBook and will also test it on an iOS phone. If you can wait until then, I'll do my best to resolve the problem and contact you again.

**Comment by ivanhercaz** [comment]
> Firstly, thank you for your compliments. I'm delighted that my package has received such recognition.

You're welcome! I think to say "thank you" is the minimum I can do when something contributes useful packages I am going to use or I plan to use.
 
> I believe I have identified the solution to your issue, which appears to be a code bug. Unfortunately, I won't be able to address it until November 2, 2023. On that day, I will have access to a MacBook and will also test it on an iOS phone. If you can wait until then, I'll do my best to resolve the problem and contact you again.

Of course! Even if you want, you can point me what you think it might be and I can try to solve it and test it. I work with Linux but I also have a MacMini to test iOS, no choice...

**Comment by ogabrielinacio** [comment]
Hey @ivanhercaz 
I'm sorry for the delay. The macOS I have is running O.S 10.13 and the minimum requirements for Flutter are 10.14. I thought I could test it in this time period and ended up having this setback. Well, I added the line
" private var cryptoAES: CryptoAES?"
to the Swift code section. I hope it fixed the initialization issue. If you have any other problems, please contact me and let me know if the problem has been resolved or not.

**Comment by ivanhercaz** [comment]
Hi @ogabrielinacio! Excuse me the delay answering you, I have been very busy and until now I couldn't test your change. I am going to test it this afternoon and I will report you if it works. If it works, I will close this issue.

Thank you very much!

**Comment by ivanhercaz** [comment]
@ogabrielinacio, f704675a07325d51b76f990aeb76b514e45ae57e seems to fix this issue. If you think #2 is not related with this issue, this issue can be closed as solved! But I prefer let you to decide it.
