### ISSUE TITLE
Connection service problem

### ISSUE THREAD

**Issue by wkk199** [ogabrielinacio/esp_provisioning_ble#14]
![企业微信截图_17133399721221](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/76580696/4152045e-8e42-4fcd-9630-06469b7cb2a7)
I am a little white not too understand, may I ask this PIN code must be filled in?

**Comment by wkk199** [comment]
![image](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/76580696/3c762b8b-7c47-4e43-9753-83cb3736150c)
Every time I get here, there's an error, and I catch it, and I'm devastated

**Comment by wkk199** [comment]
![image](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/76580696/224460da-1592-418a-adda-90106af6ff7c)
When I write to the cache, I get an error, which makes me very upset

**Comment by wkk199** [comment]
@ivanhercaz @ogabrielinacio Could you take a look at it for me if you have time?

**Comment by wkk199** [comment]
![image](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/76580696/c1909e7a-94c2-49fa-bb17-4d65b1c1a34d)
If you can't get the PIN is there no way to establish a session

**Comment by wkk199** [comment]
![image](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/76580696/fabe153a-0317-437d-9147-09f5f7d0ba48)
如果无法获取PIN是不是就没办法建立会话

**Comment by ivanhercaz** [comment]
> @ivanhercaz @ogabrielinacio Could you take a look at it for me if you have time?

We need more information about what are you trying to help you better. But by the moment just some questions:

1. Are you trying to connect with example app of the package to an ESP32?
2. If 1 is true, have you flash the ESP provisioning firmware or use its provisioning toolchain?
3. If 2 is true, have you check your ESP32 logs? Is it something strange?
4. Are you trying to connect with the default proof of possession used in the application? Remember that in this step you need to use the proof of possession you configured in your ESP32.

Tomorrow I will take a better look to the image to check if I miss something.

**Comment by ivanhercaz** [comment]
> ![image](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/76580696/fabe153a-0317-437d-9147-09f5f7d0ba48)
> 如果无法获取PIN是不是就没办法建立会话

**Translation using a translator** (sorry, I don't Chinese 😅).

> If the PIN cannot be obtained, will it be impossible to establish a session?

Of course, it isn't possible.

The PIN/proof of possession is the key that let you access to the Bluetooth device. It must be known just for the users, tools or applications that must have access to the Bluetooth device. It is part of the security modules and the Bluetooth standard for security.

**Comment by wkk199** [comment]
@ivanhercaz There is a problem Bluetooth into the hardware, so how to get the PIN code?

**Comment by ivanhercaz** [comment]
> @ivanhercaz There is a problem Bluetooth into the hardware, so how to get the PIN code?

A "problem Bluetooth into the hardware" is something with a wide scope of possible problems. In addition, if the firmware flashed on the hardware has problems with the Bluetooth or its configuration, you should ask to the firmware maintainers about it. The proof of possession (PIN code) can't be obtained with this package, you need it to connect, establish a sessions and communicate with a Bluetooth device.

> @ivanhercaz The result I want is that it is OK to connect to the network after Bluetooth, and there is no matching PIN code when writing with native, so this is more curious

I doesn't understand this part 😕 .

In https://github.com/ogabrielinacio/esp_provisioning_ble/issues/14#issuecomment-2062991703 I asked you some questions to help you debugging the problem you have. Please, answer them to have more details and try to help you better.

However, it doesn't seems related with a problem of the package or with the example given in the package.

**Comment by ivanhercaz** [comment]
I close it doesn't seems a particular issue with the package nor have answers by the reporter from more than 3 months.
