### ISSUE TITLE
Any way to get this work with Security0

### ISSUE THREAD

**Issue by garudaonekh** [ogabrielinacio/esp_provisioning_ble#6]
Hi,
Due to some problem, our ESP32 work only with Security0(i.e without any POP pin). Can this git work with that?

I run this code in Android, it can detect the ESP32, but it failed at POP PIN.

I have little knowledge on Flutter. If it works with Security1, get it to work with Security0 is simple.

Thanks;

**Comment by ogabrielinacio** [comment]
I  tried the app with the ESP32 security 1 config like `const char *pop = ""; `, and it failed, i will try to fix that. I do not tried yet the security 0 yet, i will do this in a comming future.

Your request will be added to the package's TODO list. However, i recommend using the security 1, or security 2, but security 2 is also not implemented in this package yet. For obvious security reasons, do not use security 0 if you have the option to use 1, as security level 0 simply transmits plain text without encryption.

![image](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/62192403/5a60e3a5-ecf5-4389-ad3e-02e13b2fb7b9)

Reference: 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/provisioning/provisioning.html#security-schemes

**Comment by garudaonekh** [comment]
> I tried the app with the ESP32 security 1 config like `const char *pop = ""; `, and it failed, i will try to fix that. I do not tried yet the security 0 yet, i will do this in a comming future.
> 
> Your request will be added to the package's TODO list. However, i recommend using the security 1, or security 2, but security 2 is also not implemented in this package yet. For obvious security reasons, do not use security 0 if you have the option to use 1, as security level 0 simply transmits plain text without encryption.
> 
> ![image](https://private-user-images.githubusercontent.com/62192403/289357083-5a60e3a5-ecf5-4389-ad3e-02e13b2fb7b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjE3NzgsIm5iZiI6MTcwMjIyMTQ3OCwicGF0aCI6Ii82MjE5MjQwMy8yODkzNTcwODMtNWE2MGUzYTUtZWNmNS00Mzg5LWFkM2UtMDJlMTNiMmZiN2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDE1MTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNTQxZjRiYzNlNGJiNTAyY2QwZWQ1MzM3M2YwZTdhOTIyZmNmMjM1NjU1ODMzYjU0MzIzMWMwNzNhMThiY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BMQq-OzvcqgZ0ZkvQmnTGRBqMQwW4AB7S-zYh9m50Hs)
> 
> Reference: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/provisioning/provisioning.html#security-schemes

I try your code with Security1 and it works. However, my project require Arduino and so far i can't get Security1 to work in Arduino.

**Comment by ogabrielinacio** [comment]
@garudaonekh 
This package was created and tested with an ESP32, i have not yet tested it with Arduino. 
Your PR will be included in the list, but I would like to inform you that it will not be a priority, since there are others more important before, such as the one to test and perform the example with other Bluetooth packages, being this the main one, and as you commented, I would like to try to add security 2, and if time permits, add security 0, since it is not a priority, since there is no security in the connection.
